import time
import random
import os

def game2():
    list = [1, 2, 3, 2, 3, 2, 1, 2, 3, 1, 1, 3]
    print ("Your move")
    choice = input(":")
    intch = int (choice)
    chingbing = random.choice (list)
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system ('cls')
    game()

def game():
    
    list = [1, 2, 3, 2, 3, 2, 1, 2, 3, 1, 1, 3]
    print ("Your move")
    choice = input(":")
    intch = int (choice)
    chingbing = random.choice (list)
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    var = (intch) + (chingbing)
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    chingbing = random.choice (list)
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("Damn gg")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Get rekt")
        time.sleep(2)
        exit()
        time.sleep(1)
    time.sleep(1)
    chingbing = random.choice (list)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(2)
        exit()
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    chingbing = random.choice (list)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(2)
        exit()
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(2)
        exit()
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(2)
        exit()
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 21:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    var = (intch) + (chingbing)
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        exit()
        time.sleep(1)
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        exit()
        time.sleep(1)
    time.sleep(1)
    print ("your move")
    chingbing = random.choice (list)
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    time.sleep(1)
    print ("your move")
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    var = (intch) + (chingbing)
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ("your move")
    choice = input (":")
    intch = int (choice)
    chingbing = random.choice (list)
    var = (intch) + (chingbing)
    if (intch) in (18, 19):
        print ("20")
        print ("get rekt")
        time.sleep(2)
        exit()
    if (intch) + (chingbing) == 21:
        print ("get rekt")
        time.sleep(2)
        exit()
    elif intch == 20:
        print ("Damn gg")
        time.sleep(1)
        exit()
    print ((intch) + (chingbing))
    time.sleep(1.5)
    os.system('cls')
    


print ("Do you want to start")
start = input(":")
if start == "y":
    game()
else:
    list = [1, 2, 1, 2, 2, 1, 1, 2, 1, 2]
    var = random.choice(list)
    time.sleep(1)
    os.system ('cls')
    print (var)
    time.sleep(2)
    game2()
